import { test, expect, type Page } from '@playwright/test'

type StudentCredentials = {
  email: string
  username: string
  password: string
}

const adminUsername = process.env.E2E_ADMIN_USERNAME || 'admincjtc'
const adminPassword = process.env.E2E_ADMIN_PASSWORD || 'admin@123'

async function loginAsAdmin(page: Page) {
  await page.goto('/admin/login')
  await page.getByTestId('admin-login-username').fill(adminUsername)
  await page.getByTestId('admin-login-password').fill(adminPassword)
  const loginResponsePromise = page.waitForResponse(
    (response) =>
      response.url().includes('/api/admin/auth/login') && response.request().method() === 'POST'
  )
  await page.getByTestId('admin-login-submit').click()
  const loginResponse = await loginResponsePromise
  expect(loginResponse.ok()).toBeTruthy()
  await expect(page.getByText('Pilotage global de la plateforme')).toBeVisible({ timeout: 30_000 })
}

test.describe('Admin and student critical flows', () => {
  test.describe.configure({ mode: 'serial' })

  let createdStudent: StudentCredentials | null = null

  test('admin login works', async ({ page }) => {
    await loginAsAdmin(page)
    await expect(page.getByText('Pilotage global de la plateforme')).toBeVisible()
  })

  test('admin can create a student account', async ({ page }) => {
    await loginAsAdmin(page)
    await page.goto('/admin/students')

    const suffix = Date.now()
    const fullName = `E2E Student ${suffix}`
    const email = `e2e.student.${suffix}@example.com`

    await page.getByTestId('student-create-name').fill(fullName)
    await page.getByTestId('student-create-email').fill(email)
    const createResponsePromise = page.waitForResponse(
      (response) =>
        response.url().includes('/api/admin/system/students') && response.request().method() === 'POST',
      { timeout: 90_000 }
    )
    await page.getByTestId('student-create-submit').click()
    const createResponse = await createResponsePromise
    expect(createResponse.ok()).toBeTruthy()

    await expect(page.getByTestId('student-credentials-panel')).toBeVisible({ timeout: 30_000 })
    await expect(page.getByTestId('student-credentials-copy')).toBeVisible()

    const username = (await page.getByTestId('student-credentials-username').textContent())?.trim()
    const password = (await page.getByTestId('student-credentials-password').textContent())?.trim()

    expect(username).toBeTruthy()
    expect(password).toBeTruthy()

    createdStudent = {
      email,
      username: username as string,
      password: password as string,
    }

    await page.getByTestId('student-search-input').fill(email)
    await expect(page.getByText(email)).toBeVisible()
  })

  test('student can log in with generated credentials', async ({ page }) => {
    test.skip(!createdStudent, 'Student credentials were not generated by the creation flow.')

    await page.goto('/student/login')
    await page.getByTestId('student-login-username').fill(createdStudent!.username)
    await page.getByTestId('student-login-password').fill(createdStudent!.password)
    const loginResponsePromise = page.waitForResponse(
      (response) =>
        response.url().includes('/api/student/auth/login') && response.request().method() === 'POST'
    )
    await page.getByTestId('student-login-submit').click()
    const loginResponse = await loginResponsePromise
    expect(loginResponse.ok()).toBeTruthy()
    await expect(page.getByText(createdStudent!.email)).toBeVisible({ timeout: 30_000 })
  })
})
