'use client'
import { useEffect, useState } from 'react'

const empty = { isActive: true, imageUrl: '/apropos.jpeg', name: '', titleFr: '', titleEn: '', messageFr: '', messageEn: '' }
export default function DirectorWelcomeAdmin() {
  const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('')
  useEffect(() => { fetch('/api/admin/director-welcome').then(r => r.json()).then(d => d.content && setForm(d.content)).catch(() => setNotice('Impossible de charger le contenu.')) }, [])
  const change = (key: keyof typeof empty, value: string | boolean) => setForm(current => ({ ...current, [key]: value }))
  async function upload(file?: File) { if (!file) return; setNotice('Téléversement…'); const fd = new FormData(); fd.append('file', file); const r = await fetch('/api/admin/director-welcome/upload', { method: 'POST', body: fd }); const d = await r.json(); if (!r.ok) return setNotice(d.error || 'Échec du téléversement.'); change('imageUrl', d.imageUrl); setNotice('Image téléversée. Enregistrez pour publier.') }
  async function save() { setSaving(true); setNotice(''); const r = await fetch('/api/admin/director-welcome', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); setNotice(r.ok ? 'Modifications enregistrées.' : 'Échec de l’enregistrement.') }
  const input = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-600'
  return <main className="mx-auto max-w-5xl p-5 sm:p-8"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-widest text-red-600">Page d’accueil</p><h1 className="mt-2 text-3xl font-black text-slate-950">Mot de bienvenue du DG</h1><p className="mt-2 text-slate-600">Contenu bilingue affiché juste après la bannière d’accueil.</p></div><div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><label className="block text-sm font-bold">Photo du DG</label>{form.imageUrl && <img src={form.imageUrl} alt="Aperçu" className="mt-3 aspect-[4/5] w-full rounded-xl object-cover" />}<input className="mt-4 block w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e => upload(e.target.files?.[0])} /><label className="mt-5 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isActive} onChange={e => change('isActive', e.target.checked)} />Afficher cette section</label></section><section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><label className="block text-sm font-bold">Nom<input className={input} value={form.name} onChange={e => change('name', e.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">Fonction (FR)<input className={input} value={form.titleFr} onChange={e => change('titleFr', e.target.value)} /></label><label className="block text-sm font-bold">Fonction (EN)<input className={input} value={form.titleEn} onChange={e => change('titleEn', e.target.value)} /></label></div><label className="block text-sm font-bold">Message (FR)<textarea className={input} rows={5} value={form.messageFr} onChange={e => change('messageFr', e.target.value)} /></label><label className="block text-sm font-bold">Message (EN)<textarea className={input} rows={5} value={form.messageEn} onChange={e => change('messageEn', e.target.value)} /></label><div className="flex items-center gap-4"><button onClick={save} disabled={saving} className="rounded-xl bg-[var(--admin-primary)] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Enregistrement…' : 'Enregistrer'}</button>{notice && <p className="text-sm text-slate-600">{notice}</p>}</div></section></div></main>
}
